name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build-win
      env:
        CI: true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Push Dist Node ${{ matrix.node-version }}
        path: |
          dist/*.appx
          dist/*.msi
    
    - name: Gerando uma  Tag
      id: tag
      run: |
        echo "Build Pos commit, job id: ${{ github.job }}" >> release.txt

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        body_path: release.txt
        prerelease: true
        files: |
          dist/*.appx
          dist/*.msi

    # - name: Remove old Releases
    #   uses: dev-drprasad/delete-older-releases@v0.1.0
    #   with:
    #     keep_latest: 4
    #     delete_tags: true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}