name: Build Dev Version
on:
  push:
    branches:
      - dev
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    
    - name: Zip
      run: |
        echo "Hello, to use, run npm run start" > HELP_TO_RUN.txt
        echo "have already installed NodeJS, if you are using a linux distro check if npm has been installed" >> HELP_TO_RUN.txt
        zip dev_zip_Windows_and_Linux.zip -r ./

    - name: Upload to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        name: Build dev, Run_id ${{ github.run_id }}
        body_path: release_dev.md
        files: dev_zip_Windows_and_Linux.zip
        prerelease: true
