name: Publish Dev in npm
on:
  push:
    branches:
      - dev
jobs:
  npm-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@main
      with:
        node-version: 15.x

    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.4
      with: # All of theses inputs are optional
        tag_name: "dev"
        tag_message: "v%s"
        commit_pattern: "^Release (\\S+)"
        workspace: "."
        publish_command: "npm"
        publish_args: "--non-interactive"
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Upload dev release github actions
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        name: Dev, Run_id ${{ github.run_id }}
        body_path: release_dev.md
        prerelease: true