name: Publish Dev in npm
on:
  push:
    branches:
      - dev
jobs:
  npm-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          id_run=$(echo ${{ github.run_id }} |cut -b 2-5)
          old="$(cat package.json |grep 'version'|head -1)"
          sed "s|$old|\"version\": \"23.$id_run.0beta\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - run: npm install
      - run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload dev release github actions
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: Dev, Run_id ${{ github.run_id }}
          body_path: release_dev.md
          prerelease: true