name: Electron Dev Branch Test and Publish Release
on: 
  push:
    branches: [dev, main]
jobs:
  npm-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Test
        run: npm run test
        env:
          ELECTRON_TEST: true

  Release-Linux:
    runs-on: ubuntu-latest
    needs: npm-test
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Build Packs
        run: npm run pack

      - name: Get The Bds Maneger Version
        run: |
          sudo apt install -y jq
          echo "BDS_VER=$(cat package.json| jq .version)" >> dist/release_config.txt
          echo "ELECTRON_VER=$(cat package.json| jq .devDependencies.electron|sed 's|\^||g')" >> dist/release_config.txt
          echo "BDS_API_VER=$(cat package.json| jq .devDependencies.bds_maneger_api|sed 's|\^||g')" >> dist/release_config.txt
          echo "COMMIT_ME=$(git show -s --format=%s -1)" >> dist/release_config.txt

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          retention-days: 1
          path: dist/*.*

  Release-Windows:
    runs-on: windows-latest
    needs: npm-test
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Build Packs
        run: npm run pack

      - uses: actions/upload-artifact@v2
        with:
          name: windows
          retention-days: 1
          path: dist/*.*

  Release:
    runs-on: ubuntu-latest
    needs: [npm-test, Release-Windows, Release-Linux]
    steps:
      - uses: actions/download-artifact@v2

      - name: Getting the env in the file
        run: |
          cat release_config.txt >> $GITHUB_ENV

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Bds Maneger Version ${{ env.BDS_VER }}
          tag_name: ${{ github.run_id }}
          files: '*.*'
          body: |
            The Bds Maneger With Electron ${{ env.ELECTRON_VER }},
            Bds Maneger API version ${{ env.BDS_API_VER }}
            ${{ env.COMMIT_ME }}