name: Publish Dev in npm
on: [push]
jobs:
  npm-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Test
        run: npm run test
  Release:
    runs-on: ubuntu-latest
    needs: npm-test
    steps:
      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Actions Run ID ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body_path: release.md

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 4
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}