name: Publish Dev in npm
on:
  push:
    branches:
      - dev
jobs:
  npm-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Upload dev release github actions
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: Dev, Run_id ${{ github.run_id }}
          body_path: release_dev.md
          prerelease: true
