name: Build Dev Version
on:
  push:
    branches:
      - dev
jobs:
  Windows-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build-win
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: archive-windows
        retention-days: 1
        path: |
          dist/*.msi
          dist/*.appx

  Debian-test:
    runs-on: ubuntu-latest
    needs: Windows-test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build-deb
      env:
        CI: true

    - name: Download Windows Files
      uses: actions/download-artifact@v2
      with:
       name: archive-windows
       path: dist

    - name: Upload to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        name: Build dev, Run_id ${{ github.run_id }}
        body_path: release_dev.md
        files: dist/*.*
        prerelease: true
