name: Publish Dev in npm
on: [push]
jobs:
  npm-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          id_run=$(echo ${{ github.run_id }} |cut -b 2-5)
          old="$(cat package.json |grep 'version'|head -1)"
          sed "s|$old|\"version\": \"23.$id_run.0beta\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Update
        run: npm update

      - bame: Install
        run: npm install

      - name: Publish
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}