name: Publish Dev in npm
on:
  push:
    branches:
      - dev
jobs:
  npm-dev:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/

      - run: npm install
      - run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload dev release github actions
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: Dev, Run_id ${{ github.run_id }}
          body_path: release_dev.md
          prerelease: true