name: Node.js CI
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build-win
      env:
        CI: true
    - name: Build Linux
      run-on: ubuntu-latest
      run: |
         npm build-deb