name: Node.js CI
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build-win
      env:
        CI: true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Push Dist Node ${{ matrix.node-version }}
        path: |
          dist/*.appx
          dist/*.msi

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        name: Build Commit, Run_id ${{ github.run_id }}
        body_path: release.md
        prerelease: true
        files: |
          dist/*.appx
          dist/*.msi